language: java
sudo: true
dist: trusty
jdk: oraclejdk11
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn test -B
addons:
  apt:
    packages:
      - oracle-java11-installer